// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

List fast_mlm(NumericMatrix Xr, NumericMatrix Yr);

static bool validateExported(const std::string& sig) {
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("List(*fast_mlm)(NumericMatrix,NumericMatrix)");
    }
    return signatures.find(sig) != signatures.end();
}

RCPP_MODULE(fastVAR_RcppExports) {
    Rcpp::function("fast_mlm", &fast_mlm, Rcpp::List::create(Rcpp::Named("Xr"), Rcpp::Named("Yr")));
    Rcpp::function("RcppExports_validateExported", &validateExported);
}
